# Dependencies
markdown:	redcarpet
highliter:	pygments

# Setup
title:		codeRIT
url:		https://coderit.org
description: codeRIT represents a coalition of RIT students with a mission to represent the RIT hackathon community on a national level. It focuses its attention towards increasing its relationship with other collegiate technical communities, teaching software development and entrepreneurial skills to its members, and uniting a fragmented collection of groups amongst GCCIS as one RIT group.

sass:
  sass_dir: _sass
